name: changelog_component
description: "A Flutter project built for frontend roadmap on roadmap.sh"

publish_to: 'none'


version: 0.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  package_rename: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
